### ISSUE TITLE
Update GitHub org image

### ISSUE THREAD

**Issue by silvenon** [mdx-js/design#2]
The current image of the GitHub organization ends up looking tiny on my profile:

<img width="152" alt="screen shot 2018-09-18 at 14 05 09" src="https://user-images.githubusercontent.com/471278/45686481-d3caec00-bb4c-11e8-8cbb-0ebb6c52de74.png">

I want to wear it loud and proud, so I propose using the image attached at the bottom, which doesn't have margins and takes maximum available space. The result:

<img width="154" alt="screen shot 2018-09-18 at 14 08 38" src="https://user-images.githubusercontent.com/471278/45686496-dd545400-bb4c-11e8-901b-75974d528634.png">

<details>
  <summary>GitHub org image</summary>

  ![github-org](https://user-images.githubusercontent.com/471278/45686080-bea18d80-bb4b-11e8-9b12-bedf7943798e.png)
</details>

**Comment by silvenon** [comment]
@johno ping 😄  I think it's a quick change, but makes a nice visual difference.

(The image is in the `<details>` part at the bottom, you can use that one.)

**Comment by johno** [comment]
Done!
